name: Publish package

on:
  push:
    tags: ["*"]

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  release:
    uses: tree-sitter/workflows/.github/workflows/release.yml@main
    permissions:
      contents: write
      id-token: write
      attestations: write
    with:
      generate: true
      attestations: true

  # NOTE: uncomment the packages you want to publish

  # npm:
  #   uses: tree-sitter/workflows/.github/workflows/package-npm.yml@main
  #   secrets:
  #     NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  # crates:
  #   uses: tree-sitter/workflows/.github/workflows/package-crates.yml@main
  #   secrets:
  #     CARGO_REGISTRY_TOKEN: ${{secrets.CARGO_TOKEN}}

  # pypi:
  #   uses: tree-sitter/workflows/.github/workflows/package-pypi.yml@main
  #   secrets:
  #     PYPI_API_TOKEN: ${{secrets.PYPI_TOKEN}}
